<?php
/**
 * STUDY NOTES FOR REVIEW
 * Purpose: Guest directory page/controller for delete. It manages saved guest profiles, restrictions, exports, or details.
 * Flow: Browser-accessible route: load config/includes, protect access if needed, handle GET/POST, call modules or SQL, then render HTML.
 * Security: Role checks, CSRF checks, prepared statements, and escaped output are used here to protect forms and direct URL access.
 */
/**
 * guests/delete.php - Admin-only guest deletion endpoint
 */
require_once __DIR__ . '/../../config/db.php';
require_once __DIR__ . '/../../config/constants.php';
require_once __DIR__ . '/../../includes/auth.php';
require_once __DIR__ . '/../../includes/helpers.php';
require_once __DIR__ . '/../../modules/guests/guests_module.php';

// Study security: role-based access control blocks users from opening this page by URL unless their role is allowed.
requireRole(ROLE_ADMIN);

if (!isPost()) {
    // Study flow: redirect after this step moves the user to the next page and helps avoid duplicate form submissions.
    redirect(APP_URL . '/public/guests/list.php');
}

$db = getDB();
$guestId = inputInt('guest_id', 'POST');
$returnTo = $_POST['return_to'] ?? APP_URL . '/public/guests/list.php';
if (!str_starts_with($returnTo, APP_URL . '/public/guests/')) {
    $returnTo = APP_URL . '/public/guests/list.php';
}

// Study security: CSRF validation confirms this POST came from a form generated by this system.
verifyCsrf($returnTo);

$guest = $guestId > 0 ? getGuestById($db, $guestId) : false;
if (!$guest) {
    setFlash('error', 'Guest not found.');
    // Study flow: redirect after this step moves the user to the next page and helps avoid duplicate form submissions.
    redirect(APP_URL . '/public/guests/list.php');
}

$err = deleteGuest($db, $guestId);
if ($err) {
    setFlash('error', $err);
    // Study flow: redirect after this step moves the user to the next page and helps avoid duplicate form submissions.
    redirect($returnTo);
}

// Study audit: this records the important action in activity_logs for review and accountability.
logActivity(null, 'other', currentUserId(), null, "Guest #{$guestId} ({$guest['full_name']}) deleted");
setFlash('success', 'Guest record deleted.');
// Study flow: redirect after this step moves the user to the next page and helps avoid duplicate form submissions.
redirect(APP_URL . '/public/guests/list.php');
