<?php
/**
 * STUDY NOTES FOR REVIEW
 * Purpose: Guest directory page/controller for lift restriction. It manages saved guest profiles, restrictions, exports, or details.
 * Flow: Browser-accessible route: load config/includes, protect access if needed, handle GET/POST, call modules or SQL, then render HTML.
 * Security: Role checks, CSRF checks, prepared statements, and escaped output are used here to protect forms and direct URL access.
 */
/**
 * guests/lift_restriction.php
 * Admin: Lift/remove an active restriction from a guest
 */
require_once __DIR__ . '/../../config/db.php';
require_once __DIR__ . '/../../config/constants.php';
require_once __DIR__ . '/../../includes/auth.php';
require_once __DIR__ . '/../../includes/helpers.php';
require_once __DIR__ . '/../../modules/guests/guests_module.php';

// Study security: role-based access control blocks users from opening this page by URL unless their role is allowed.
requireRole(ROLE_ADMIN);
$db = getDB();

$guestId = (int) ($_GET['id'] ?? 0);
// Study flow: redirect after this step moves the user to the next page and helps avoid duplicate form submissions.
if (!$guestId) redirect(APP_URL . '/public/guests/restricted.php');

// Study query: Prepared SQL: reads rows from guests for lookup, validation, or display. Placeholders keep user/form values separate from the SQL text.
$gStmt = $db->prepare("SELECT * FROM guests WHERE guest_id=:id AND is_restricted=1");
$gStmt->execute([':id' => $guestId]);
$guest = $gStmt->fetch();
if (!$guest) {
    setFlash('info', 'This guest is not restricted or does not exist.');
    // Study flow: redirect after this step moves the user to the next page and helps avoid duplicate form submissions.
    redirect(APP_URL . '/public/guests/restricted.php');
}

if (!isPost()) {
    $pageTitle = 'Lift Restriction';
    // Study flow: controller work is done above; the shared header starts the visible page layout below.
    include __DIR__ . '/../../includes/header.php';
    ?>
    <div class="page-top">
      <div>
        <div class="page-title">Lift Restriction</div>
        <ul class="breadcrumb">
          <li><a href="<?= APP_URL ?>/public/guests/restricted.php">Restricted Guests</a></li>
          <li><?= e($guest['full_name']) ?></li>
        </ul>
      </div>
    </div>

    <div class="info-box warning" style="margin-bottom:20px;">
      <i data-lucide="alert-triangle"></i>
      <div>You are about to allow <strong><?= e($guest['full_name']) ?></strong> to be processed for future campus visits again.</div>
    </div>

    <div class="form-card">
      <div class="card">
        <div class="card-header"><i data-lucide="shield-check" style="width:16px;height:16px;vertical-align:middle;margin-right:6px;"></i>Confirm Action</div>
        <div class="card-body">
          <form method="POST">
            <?= csrfField() ?>
            <div style="display:flex;gap:10px;">
              <button type="submit" class="btn btn-success"><i data-lucide="shield-check"></i> Lift Restriction</button>
              <a href="<?= APP_URL ?>/public/guests/view.php?id=<?= $guestId ?>" class="btn btn-outline">Cancel</a>
            </div>
          </form>
        </div>
      </div>
    </div>
    <script>lucide.createIcons();</script>
    <?php
    include __DIR__ . '/../../includes/footer.php';
    exit;
}

// Study security: CSRF validation confirms this POST came from a form generated by this system.
verifyCsrf(APP_URL . '/public/guests/lift_restriction.php?id=' . $guestId);

// Study transaction: several related database changes must succeed together or be rolled back together.
$db->beginTransaction();

// Lift restriction record
// Study query: Prepared SQL: updates existing row(s) in RESTRICTED_GUESTS. Placeholders keep user/form values separate from the SQL text.
$db->prepare("
    UPDATE restricted_guests
    SET is_active = 0, lifted_at = NOW(), lifted_by_user_id = :uid
    WHERE guest_id = :gid AND is_active = 1
")->execute([':uid' => currentUserId(), ':gid' => $guestId]);

// Update guest flag
// Study query: Prepared SQL: updates existing row(s) in GUESTS. Placeholders keep user/form values separate from the SQL text.
$db->prepare("UPDATE guests SET is_restricted=0, restriction_reason=NULL WHERE guest_id=:id")
   ->execute([':id' => $guestId]);

// Study audit: this records the important action in activity_logs for review and accountability.
logActivity(null, 'other', currentUserId(), null,
    "Restriction lifted for guest '{$guest['full_name']}' (ID:{$guestId}) by admin");

// Study transaction: commit saves all database changes made since beginTransaction().
$db->commit();

setFlash('success', "Restriction for <strong>{$guest['full_name']}</strong> has been lifted. Guest is now allowed campus access.");
// Study flow: redirect after this step moves the user to the next page and helps avoid duplicate form submissions.
redirect(APP_URL . '/public/guests/view.php?id=' . $guestId);
