<?php
/**
 * STUDY NOTES FOR REVIEW
 * Purpose: Admin page/controller for offices. It manages users, offices, or audit information.
 * Flow: Browser-accessible route: load config/includes, protect access if needed, handle GET/POST, call modules or SQL, then render HTML.
 * Security: Role checks, CSRF checks, prepared statements, and escaped output are used here to protect forms and direct URL access.
 */
/**
 * admin/offices.php — Office Management
 */
require_once __DIR__ . '/../../config/db.php';
require_once __DIR__ . '/../../config/constants.php';
require_once __DIR__ . '/../../includes/auth.php';
require_once __DIR__ . '/../../includes/helpers.php';
require_once __DIR__ . '/../../modules/admin/users_module.php';
require_once __DIR__ . '/../../modules/admin/offices_module.php';
// Study security: role-based access control blocks users from opening this page by URL unless their role is allowed.
requireRole(ROLE_ADMIN);
$pageTitle = 'Manage Offices';
$db = getDB();

if (isPost() && isset($_POST['toggle_status'])) {
    // Study security: CSRF validation confirms this POST came from a form generated by this system.
    verifyCsrf(APP_URL . '/public/admin/offices.php');
    $oid = (int)$_POST['office_id']; $new = $_POST['current_status']==='active'?'inactive':'active';
    // Study query: Prepared SQL: updates existing row(s) in OFFICES. Placeholders keep user/form values separate from the SQL text.
    $db->prepare("UPDATE offices SET status=:s WHERE office_id=:id")->execute([':s'=>$new,':id'=>$oid]);
    // Study flow: redirect after this step moves the user to the next page and helps avoid duplicate form submissions.
    setFlash('success','Office status updated.'); redirect(APP_URL.'/public/admin/offices.php');
}
if (isPost() && isset($_POST['add_office'])) {
    // Study security: CSRF validation confirms this POST came from a form generated by this system.
    verifyCsrf(APP_URL . '/public/admin/offices.php');
    $name = trim($_POST['office_name']??''); $loc = trim($_POST['office_location']??'');
    if (!empty($name)) {
        $code = generateUniqueOfficeCode($db, $name);
        // Study query: Prepared SQL: creates a new row in OFFICES. Placeholders keep user/form values separate from the SQL text.
        $db->prepare("INSERT INTO offices (office_name,office_code,office_location,status) VALUES (:n,:c,:l,'active')")
           ->execute([':n'=>$name,':c'=>$code,':l'=>$loc?:null]);
        setFlash('success',"Office <strong>{$name}</strong> added.");
    // Study flow: redirect after this step moves the user to the next page and helps avoid duplicate form submissions.
    } redirect(APP_URL.'/public/admin/offices.php');
}

// Study query: SQL query: reads rows from users, offices for lookup, validation, or display.
$offices = $db->query("SELECT o.*, (SELECT COUNT(*) FROM users u WHERE u.office_id=o.office_id AND u.status='active') AS staff_count FROM offices o ORDER BY o.office_name")->fetchAll();
$total = count($offices);
// Study flow: controller work is done above; the shared header starts the visible page layout below.
include __DIR__ . '/../../includes/header.php';
?>

<div class="page-top">
  <div>
    <div class="page-title">Manage Offices</div>
    <ul class="breadcrumb"><li><a href="<?= APP_URL ?>/public/dashboard/admin.php">Dashboard</a></li><li>Offices</li></ul>
  </div>
  <div class="page-actions">
    <button type="button" class="btn btn-primary" onclick="document.getElementById('addPanel').style.display=document.getElementById('addPanel').style.display==='none'?'block':'none'">
      <i data-lucide="plus"></i> Add Office
    </button>
  </div>
</div>

<!-- Quick Add -->
<div class="card" id="addPanel" style="display:none;margin-bottom:20px;">
  <div class="card-header">Add New Office</div>
  <div class="card-body">
    <form method="POST" style="display:flex;gap:12px;flex-wrap:wrap;align-items:flex-end;">
      <?= csrfField() ?>
      <div class="form-group" style="flex:1;min-width:200px;margin-bottom:0;">
        <label class="form-label">Office Name <span class="required-star">*</span></label>
        <input type="text" name="office_name" class="form-control" required placeholder="e.g. Registrar's Office">
      </div>
      <div class="form-group" style="flex:1;min-width:200px;margin-bottom:0;">
        <label class="form-label">Location</label>
        <input type="text" name="office_location" class="form-control" placeholder="e.g. Admin Bldg, 2nd Floor">
      </div>
      <button type="submit" name="add_office" class="btn btn-primary" style="height:38px;"><i data-lucide="plus"></i> Add</button>
    </form>
  </div>
</div>

<div class="card">
  <div class="table-toolbar">
    <div class="table-search"><i data-lucide="search" class="table-search-icon"></i>
      <input type="text" id="searchInput" placeholder="Search offices…" autocomplete="off"></div>
    <select class="table-filter" id="statusFilter">
      <option value="">All Status</option><option value="active">Active</option><option value="inactive">Inactive</option>
    </select>
    <div class="table-count"><span id="visibleCount"><?= $total ?></span> of <?= $total ?> offices</div>
  </div>
  <div class="table-responsive">
    <table class="data-table" id="tbl">
      <thead><tr><th>Office Name</th><th>Location</th><th>Staff</th><th>Status</th><th>Actions</th></tr></thead>
      <tbody>
      <?php foreach ($offices as $o): ?>
      <tr data-status="<?= $o['status'] ?>">
        <td style="font-weight:600;"><?= e($o['office_name']) ?></td>
        <td style="font-size:.83rem;color:var(--text-s);"><?= e($o['office_location'] ?? '—') ?></td>
        <td><span class="badge badge-blue"><?= (int)$o['staff_count'] ?> staff</span></td>
        <td><span class="badge <?= $o['status']==='active'?'badge-success':'badge-danger' ?>"><?= ucfirst($o['status']) ?></span></td>
        <td>
          <div class="tbl-actions">
            <a href="<?= APP_URL ?>/public/admin/edit_office.php?id=<?= $o['office_id'] ?>" class="btn-tbl btn-tbl-outline"><i data-lucide="pencil"></i> Edit</a>
            <form method="POST" style="display:inline;">
              <?= csrfField() ?>
              <input type="hidden" name="office_id" value="<?= $o['office_id'] ?>">
              <input type="hidden" name="current_status" value="<?= $o['status'] ?>">
              <button type="submit" name="toggle_status" class="btn-tbl <?= $o['status']==='active'?'btn-tbl-warn':'btn-tbl-success' ?>">
                <i data-lucide="<?= $o['status']==='active'?'eye-off':'eye' ?>"></i> <?= $o['status']==='active'?'Deactivate':'Activate' ?>
              </button>
            </form>
          </div>
        </td>
      </tr>
      <?php endforeach; ?>
      </tbody>
    </table>
  </div>
</div>

<script>
const s=document.getElementById('searchInput'),f=document.getElementById('statusFilter'),t=document.getElementById('tbl'),c=document.getElementById('visibleCount');
function filter(){const q=s.value.toLowerCase().trim(),st=f.value;let n=0;
t.querySelectorAll('tbody tr[data-status]').forEach(r=>{const ok=(!q||r.textContent.toLowerCase().includes(q))&&(!st||r.dataset.status===st);r.style.display=ok?'':'none';if(ok)n++;});c.textContent=n;}
let d;s.addEventListener('input',()=>{clearTimeout(d);d=setTimeout(filter,200);});f.addEventListener('change',filter);
lucide.createIcons();
</script>
<?php include __DIR__ . '/../../includes/footer.php'; ?>
