<?php
/**
 * STUDY NOTES FOR REVIEW
 * Purpose: Guest House page/controller for bookings. It connects forms and views to Guest House booking/room modules.
 * Flow: Browser-accessible route: load config/includes, protect access if needed, handle GET/POST, call modules or SQL, then render HTML.
 * Security: Role checks, CSRF checks, prepared statements, and escaped output are used here to protect forms and direct URL access.
 */
/**
 * public/guest_house/bookings.php - Expected Guest House guests
 */
require_once __DIR__ . '/../../config/db.php';
require_once __DIR__ . '/../../config/constants.php';
require_once __DIR__ . '/../../includes/auth.php';
require_once __DIR__ . '/../../includes/helpers.php';
require_once __DIR__ . '/../../modules/guest_house/gh_bookings_module.php';

// Study security: role-based access control blocks users from opening this page by URL unless their role is allowed.
requireRole([ROLE_ADMIN, ROLE_GUEST_HOUSE_STAFF]);
$pageTitle = 'Guest House - Expected Guests';
$db = getDB();

if (isPost()) {
    // Study security: CSRF validation confirms this POST came from a form generated by this system.
    verifyCsrf(APP_URL . '/public/guest_house/bookings.php');
    $bid = inputInt('booking_id', 'POST');

    if (isset($_POST['do_arrived'])) {
        $err = ghCheckIn($db, $bid, currentUserId());
        $err ? setFlash('error', $err) : setFlash('success', 'Guest marked as arrived.');
    } elseif (isset($_POST['do_left'])) {
        $err = ghCheckOut($db, $bid, currentUserId());
        $err ? setFlash('error', $err) : setFlash('success', 'Guest marked as left.');
    }

    // Study flow: redirect after this step moves the user to the next page and helps avoid duplicate form submissions.
    redirect(APP_URL . '/public/guest_house/bookings.php');
}

$filters = [
    'status' => inputStr('status', 'GET'),
    'q'      => inputStr('q', 'GET'),
    'from'   => inputStr('from', 'GET'),
    'to'     => inputStr('to', 'GET'),
];
$bookings = ghListBookings($db, $filters);

// Study flow: controller work is done above; the shared header starts the visible page layout below.
include __DIR__ . '/../../includes/header.php';
?>

<div class="page-top">
  <div>
    <div class="page-title">Expected Guests</div>
    <ul class="breadcrumb">
      <li><a href="<?= APP_URL ?>/public/dashboard/guest_house.php">Guest House</a></li>
      <li>Expected Guests</li>
    </ul>
  </div>
  <div class="page-actions">
    <a href="<?= APP_URL ?>/public/guest_house/booking_create.php" class="btn btn-primary">
      <i data-lucide="calendar-plus"></i> Add Expected Guest
    </a>
  </div>
</div>

<div class="card">
  <form method="GET" class="table-toolbar" style="flex-wrap:wrap;">
    <div class="table-search">
      <i data-lucide="search" class="table-search-icon"></i>
      <input type="text" name="q" value="<?= e($filters['q']) ?>" placeholder="Search name, reference, or organization">
    </div>
    <select name="status" class="table-filter">
      <option value="">All Status</option>
      <?php foreach (['reserved', 'checked_in', 'checked_out', 'cancelled'] as $s): ?>
      <option value="<?= $s ?>" <?= ($filters['status'] === $s) ? 'selected' : '' ?>><?= statusLabel($s) ?></option>
      <?php endforeach; ?>
    </select>
    <input type="date" name="from" value="<?= e($filters['from']) ?>" class="table-filter" title="From">
    <input type="date" name="to" value="<?= e($filters['to']) ?>" class="table-filter" title="To">
    <button class="btn btn-outline"><i data-lucide="filter"></i> Filter</button>
    <a class="btn btn-outline" href="<?= APP_URL ?>/public/guest_house/bookings.php"><i data-lucide="x"></i> Reset</a>
    <div class="table-count"><?= count($bookings) ?> records</div>
  </form>

  <div class="table-responsive">
    <table class="data-table">
      <thead><tr>
        <th>Reference</th><th>Guest</th><th>Room</th><th>Stay Dates</th><th>Status</th><th>Actions</th>
      </tr></thead>
      <tbody>
      <?php if (empty($bookings)): ?>
      <tr><td colspan="6" style="text-align:center;padding:32px;color:var(--text-m);">No expected guests found.</td></tr>
      <?php else: foreach ($bookings as $b): ?>
      <tr>
        <td><code style="font-size:.8rem;background:var(--bg);padding:2px 6px;border-radius:4px;"><?= e($b['booking_reference']) ?></code></td>
        <td>
          <div class="guest-cell">
            <div class="guest-avatar"><?= strtoupper(substr($b['guest_name'], 0, 1)) ?></div>
            <div>
              <div class="guest-name"><?= e($b['guest_name']) ?></div>
              <?php if (!empty($b['organization'])): ?>
              <div class="guest-ref"><?= e($b['organization']) ?></div>
              <?php endif; ?>
              <?php if (!empty($b['contact_number'])): ?>
              <div class="guest-ref"><?= e($b['contact_number']) ?></div>
              <?php endif; ?>
            </div>
          </div>
        </td>
        <td>
          <?php if (!empty($b['room_number'])): ?>
            <strong><?= e($b['room_number']) ?></strong>
            <div style="font-size:.75rem;color:var(--text-m);"><?= e($b['type_name'] ?? '') ?></div>
          <?php else: ?>
            <span style="color:var(--text-m);">Unassigned</span>
          <?php endif; ?>
        </td>
        <td style="font-size:.83rem;">
          <?= formatDate($b['check_in_date']) ?><br>
          <span style="color:var(--text-m);">to <?= formatDate($b['check_out_date']) ?></span>
        </td>
        <td>
          <span class="badge <?= match ($b['status']) {
              'reserved' => 'badge-warning',
              'checked_in', 'occupied' => 'badge-success',
              'checked_out' => 'badge-secondary',
              'cancelled' => 'badge-danger',
              default => 'badge-secondary',
          } ?>"><?= statusLabel($b['status']) ?></span>
        </td>
        <td>
          <div class="tbl-actions">
            <a href="booking_view.php?id=<?= (int)$b['booking_id'] ?>" class="btn-tbl btn-tbl-outline">
              <i data-lucide="eye"></i> View
            </a>
            <?php if ($b['status'] === 'reserved' && !empty($b['room_id'])): ?>
            <form method="POST" style="display:inline;">
              <?= csrfField() ?>
              <input type="hidden" name="booking_id" value="<?= (int)$b['booking_id'] ?>">
              <button type="submit" name="do_arrived" class="btn-tbl btn-tbl-success" data-confirm="Mark this guest as arrived?">
                <i data-lucide="log-in"></i> Arrived
              </button>
            </form>
            <?php endif; ?>
            <?php if (in_array($b['status'], ['checked_in', 'occupied'], true)): ?>
            <form method="POST" style="display:inline;">
              <?= csrfField() ?>
              <input type="hidden" name="booking_id" value="<?= (int)$b['booking_id'] ?>">
              <button type="submit" name="do_left" class="btn-tbl btn-tbl-warn" data-confirm="Mark this guest as left?">
                <i data-lucide="log-out"></i> Left
              </button>
            </form>
            <?php endif; ?>
          </div>
        </td>
      </tr>
      <?php endforeach; endif; ?>
      </tbody>
    </table>
  </div>
</div>

<script>lucide.createIcons();</script>
<?php include __DIR__ . '/../../includes/footer.php'; ?>
